#Docker version to use
version: '3'

#Container services
services:

    zookeeper:
        container_name: zookeeper
        # official docker Apache Zookeeper image
        image: cfei/zookeeper:latest-multiarch
        networks:
            - kafka_network
        hostname: zookeeper
        environment: 
            ZOO_ID: 1  
            ZOO_PORT: 2181
            ZOO_TICK_TIME: 2000
            ZOO_MAX_SESSION_TIMEOUT: 60000
        restart: always #no, always, on-failure, unless-stopped

    kafka:
        container_name: kafka
        image: cfei/kafka:latest-multiarch
        depends_on:
            - zookeeper
        networks:
            - kafka_network
        hostname: kafka
        environment: 
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9093
            KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        restart: always #no, always, on-failure, unless-stopped

    producer:
        container_name: producer
        image: producer
        depends_on: 
            - zookeeper
            - kafka
        networks: 
            - kafka_network
        build:
            context: producer/
            dockerfile: Dockerfile
        command: ["python3", "producer.py"]

    consumer:
        container_name: consumer
        image: consumer
        depends_on: 
            - zookeeper
            - kafka
            - producer
        networks: 
            - kafka_network
        build:
            context: consumer/
            dockerfile: Dockerfile
        command: ["python3", "consumer.py"]

networks:
    kafka_network:
        name: kafka_network
        driver: bridge